name: FurniCraft Pro CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Import data
      run: npm run import-data
      
    - name: Check for syntax errors
      run: node -c *.js
      
    - name: Start server for testing (background)
      run: npm start &
      
    - name: Wait for server to start
      run: sleep 5
      
    - name: Test server response
      run: curl -sSf http://localhost:3001/ || exit 1
      
    - name: Create build artifacts
      run: |
        mkdir -p dist
        cp -r public data *.js package*.json dist/
        cd dist && npm ci --production
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: dist/ 